saint_config_jan='{ "devices":[
{ "jour": "01", "nom": "Jour de l An"},
{ "jour": "02", "nom": "Basile"},
{ "jour": "03", "nom": "Geneviève"},
{ "jour": "04", "nom": "Odilon"},
{ "jour": "05", "nom": "Edouard"},
{ "jour": "06", "nom": "Mélaine"},
{ "jour": "07", "nom": "Raymond"},
{ "jour": "08", "nom": "Lucien"},
{ "jour": "09", "nom": "Alix"},
{ "jour": "10", "nom": "Guillaume"},
{ "jour": "11", "nom": "Paulin"},
{ "jour": "12", "nom": "Tatiana"},
{ "jour": "13", "nom": "Yvette"},
{ "jour": "14", "nom": "Nina"},
{ "jour": "15", "nom": "Rémi"},
{ "jour": "16", "nom": "Marcel"},
{ "jour": "17", "nom": "Roseline"},
{ "jour": "18", "nom": "Prisca"},
{ "jour": "19", "nom": "Marius"},
{ "jour": "20", "nom": "Sébastien"},
{ "jour": "21", "nom": "Agnès"},
{ "jour": "22", "nom": "Vincent"},
{ "jour": "23", "nom": "Barnard"},
{ "jour": "24", "nom": "François de Sales"},
{ "jour": "25", "nom": "Conv. St Paul"},
{ "jour": "26", "nom": "Paule"},
{ "jour": "27", "nom": "Angèle"},
{ "jour": "28", "nom": "Thérèse d aquin"},
{ "jour": "29", "nom": "Gildas"},
{ "jour": "30", "nom": "Martine"},
{ "jour": "31", "nom": "Marcelle"}
]}' 

saint_config_fev='{ "devices":[
{ "jour": "01", "nom": "Ella"},
{ "jour": "02", "nom": "Présentation"},
{ "jour": "03", "nom": "Blaise"},
{ "jour": "04", "nom": "Véronique"},
{ "jour": "05", "nom": "Agathe"},
{ "jour": "06", "nom": "Gaston"},
{ "jour": "07", "nom": "Eugénie"},
{ "jour": "08", "nom": "Jacqueline"},
{ "jour": "09", "nom": "Apolline"},
{ "jour": "10", "nom": "Arnaud"},
{ "jour": "11", "nom": "N.D. Lourdes"},
{ "jour": "12", "nom": "Félix"},
{ "jour": "13", "nom": "Béatrice"},
{ "jour": "14", "nom": "Valentin"},
{ "jour": "15", "nom": "Claude"},
{ "jour": "16", "nom": "Julienne"},
{ "jour": "17", "nom": "Alexis"},
{ "jour": "18", "nom": "Bernadette"},
{ "jour": "19", "nom": "Gabin"},
{ "jour": "20", "nom": "Aimée"},
{ "jour": "21", "nom": "P. Damien"},
{ "jour": "22", "nom": "Isabelle"},
{ "jour": "23", "nom": "Lazare"},
{ "jour": "24", "nom": "Modeste"},
{ "jour": "25", "nom": "Roméo"},
{ "jour": "26", "nom": "Nestor"},
{ "jour": "27", "nom": "Honorine"},
{ "jour": "28", "nom": "Romain"}
]}' 

saint_config_mar='{ "devices":[
{ "jour": "01", "nom": "Aubin"},
{ "jour": "02", "nom": "Charles le B"},
{ "jour": "03", "nom": "Guénolé"},
{ "jour": "04", "nom": "Casimir"},
{ "jour": "05", "nom": "Olive"},
{ "jour": "06", "nom": "Colette"},
{ "jour": "07", "nom": "Félicité"},
{ "jour": "08", "nom": "Jean de dieu"},
{ "jour": "09", "nom": "Françoise"},
{ "jour": "10", "nom": "Vivien"},
{ "jour": "11", "nom": "Rosine"},
{ "jour": "12", "nom": "Justine"},
{ "jour": "13", "nom": "Rodrigue"},
{ "jour": "14", "nom": "Mathilde"},
{ "jour": "15", "nom": "Louise"},
{ "jour": "16", "nom": "Bénédicte"},
{ "jour": "17", "nom": "Patrice"},
{ "jour": "18", "nom": "Cyrille"},
{ "jour": "19", "nom": "Joseph"},
{ "jour": "20", "nom": "Herbert"},
{ "jour": "21", "nom": "Clémence"},
{ "jour": "22", "nom": "Léa"},
{ "jour": "23", "nom": "Victorien"},
{ "jour": "24", "nom": "Cath. de Suède"},
{ "jour": "25", "nom": "Humbert"},
{ "jour": "26", "nom": "Larissa"},
{ "jour": "27", "nom": "Habib"},
{ "jour": "28", "nom": "Gontran"},
{ "jour": "29", "nom": "Gwladys"},
{ "jour": "30", "nom": "Amédée"},
{ "jour": "31", "nom": "Benjamin"}
]}' 

saint_config_avr='{ "devices":[
{ "jour": "01", "nom": "Hugues"},
{ "jour": "02", "nom": "Sandrine"},
{ "jour": "03", "nom": "Richard"},
{ "jour": "04", "nom": "Isidore"},
{ "jour": "05", "nom": "Irène"},
{ "jour": "06", "nom": "Marcellin"},
{ "jour": "07", "nom": "Jean-Bapt. de la Salle"},
{ "jour": "08", "nom": "Julie"},
{ "jour": "09", "nom": "Gautier"},
{ "jour": "10", "nom": "Fulbert"},
{ "jour": "11", "nom": "Stanislas"},
{ "jour": "12", "nom": "Jules"},
{ "jour": "13", "nom": "Ida"},
{ "jour": "14", "nom": "Maxime"},
{ "jour": "15", "nom": "Paterne"},
{ "jour": "16", "nom": "Benoît"},
{ "jour": "17", "nom": "Anicet"},
{ "jour": "18", "nom": "Parfait"},
{ "jour": "19", "nom": "Emma"},
{ "jour": "20", "nom": "Odette"},
{ "jour": "21", "nom": "Anselme"},
{ "jour": "22", "nom": "Alexandre"},
{ "jour": "23", "nom": "Georges"},
{ "jour": "24", "nom": "Fidele"},
{ "jour": "25", "nom": "Marc"},
{ "jour": "26", "nom": "Alida"},
{ "jour": "27", "nom": "Zita"},
{ "jour": "28", "nom": "Valérie"},
{ "jour": "29", "nom": "Catherine"},
{ "jour": "30", "nom": "Robert"}
]}' 

saint_config_mai='{ "devices":[
{ "jour": "01", "nom": "Fête du Travail"},
{ "jour": "02", "nom": "Boris"},
{ "jour": "03", "nom": "Philippe et Jacques"},
{ "jour": "04", "nom": "Sylvain"},
{ "jour": "05", "nom": "Judith"},
{ "jour": "06", "nom": "Prudence"},
{ "jour": "07", "nom": "Gisèle"},
{ "jour": "08", "nom": "Victoire 1945"},
{ "jour": "09", "nom": "Pacôme"},
{ "jour": "10", "nom": "Solange"},
{ "jour": "11", "nom": "Estelle"},
{ "jour": "12", "nom": "Achille"},
{ "jour": "13", "nom": "Rolande"},
{ "jour": "14", "nom": "Matthias"},
{ "jour": "15", "nom": "Denise"},
{ "jour": "16", "nom": "Honoré"},
{ "jour": "17", "nom": "Pascal"},
{ "jour": "18", "nom": "Eric"},
{ "jour": "19", "nom": "Yves"},
{ "jour": "20", "nom": "Bernardin"},
{ "jour": "21", "nom": "Constantin"},
{ "jour": "22", "nom": "Emile"},
{ "jour": "23", "nom": "Didier"},
{ "jour": "24", "nom": "Donatien"},
{ "jour": "25", "nom": "Sophie"},
{ "jour": "26", "nom": "Bérenger"},
{ "jour": "27", "nom": "Augustin"},
{ "jour": "28", "nom": "Germain"},
{ "jour": "29", "nom": "Aymard"},
{ "jour": "30", "nom": "Ferdinand"},
{ "jour": "31", "nom": "Visitation"}
]}' 

saint_config_jui='{ "devices":[
{ "jour": "01", "nom": "Justin et Renan"},
{ "jour": "02", "nom": "Blandine"},
{ "jour": "03", "nom": "Kevin"},
{ "jour": "04", "nom": "Clotilde"},
{ "jour": "05", "nom": "Igor"},
{ "jour": "06", "nom": "Norbert"},
{ "jour": "07", "nom": "Gilbert"},
{ "jour": "08", "nom": "Médard"},
{ "jour": "09", "nom": "Diane"},
{ "jour": "10", "nom": "Landry"},
{ "jour": "11", "nom": "Barnabe"},
{ "jour": "12", "nom": "Guy"},
{ "jour": "13", "nom": "Antoine de P."},
{ "jour": "14", "nom": "Elisée"},
{ "jour": "15", "nom": "Germaine"},
{ "jour": "16", "nom": "J.F. Régis"},
{ "jour": "17", "nom": "Hervé"},
{ "jour": "18", "nom": "Leonce"},
{ "jour": "19", "nom": "Romuald"},
{ "jour": "20", "nom": "Silvère"},
{ "jour": "21", "nom": "Rodolphe"},
{ "jour": "22", "nom": "Alban"},
{ "jour": "23", "nom": "Audrey"},
{ "jour": "24", "nom": "Jean-baptiste"},
{ "jour": "25", "nom": "Prosper"},
{ "jour": "26", "nom": "Anthelme"},
{ "jour": "27", "nom": "Fernand"},
{ "jour": "28", "nom": "Irènée"},
{ "jour": "29", "nom": "Pierre, Paul"},
{ "jour": "30", "nom": "Martial"}
]}' 

saint_config_juillet='{ "devices":[
{ "jour": "01", "nom": "Thierry"},
{ "jour": "02", "nom": "Martinien"},
{ "jour": "03", "nom": "Thomas"},
{ "jour": "04", "nom": "Florent"},
{ "jour": "05", "nom": "Antoine"},
{ "jour": "06", "nom": "Mariette"},
{ "jour": "07", "nom": "Raoul"},
{ "jour": "08", "nom": "Thibaut"},
{ "jour": "09", "nom": "Amandine"},
{ "jour": "10", "nom": "Ulrich"},
{ "jour": "11", "nom": "Benoît"},
{ "jour": "12", "nom": "Olivier"},
{ "jour": "13", "nom": "Henri et Joël"},
{ "jour": "14", "nom": "Fête Nationale"},
{ "jour": "15", "nom": "Donald"},
{ "jour": "16", "nom": "N.D. Mt Carmel"},
{ "jour": "17", "nom": "Charlotte"},
{ "jour": "18", "nom": "Frédéric"},
{ "jour": "19", "nom": "Arsène"},
{ "jour": "20", "nom": "Marina"},
{ "jour": "21", "nom": "Victor"},
{ "jour": "22", "nom": "Marie-Mad."},
{ "jour": "23", "nom": "Brigitte"},
{ "jour": "24", "nom": "Christine"},
{ "jour": "25", "nom": "Jacques"},
{ "jour": "26", "nom": "Anne"},
{ "jour": "27", "nom": "Nathalie"},
{ "jour": "28", "nom": "Samson"},
{ "jour": "29", "nom": "Marthe"},
{ "jour": "30", "nom": "Juliette"},
{ "jour": "31", "nom": "Ignace"}
]}' 

saint_config_aou='{ "devices":[
{ "jour": "01", "nom": "Alphonse"},
{ "jour": "02", "nom": "Julien"},
{ "jour": "03", "nom": "Lydie"},
{ "jour": "04", "nom": "Jean-Marie Vianney"},
{ "jour": "05", "nom": "Abel"},
{ "jour": "06", "nom": "Transfiguration"},
{ "jour": "07", "nom": "Gaétan"},
{ "jour": "08", "nom": "Dominique"},
{ "jour": "09", "nom": "Amour"},
{ "jour": "10", "nom": "Laurent"},
{ "jour": "11", "nom": "Claire"},
{ "jour": "12", "nom": "Clarisse"},
{ "jour": "13", "nom": "Hippolyte"},
{ "jour": "14", "nom": "Evrard"},
{ "jour": "15", "nom": "Assomption et Marie"},
{ "jour": "16", "nom": "Armel"},
{ "jour": "17", "nom": "Hyacinthe"},
{ "jour": "18", "nom": "Hélène"},
{ "jour": "19", "nom": "Jean Eudes"},
{ "jour": "20", "nom": "Bernard"},
{ "jour": "21", "nom": "Christophe"},
{ "jour": "22", "nom": "Fabrice"},
{ "jour": "23", "nom": "Rose"},
{ "jour": "24", "nom": "Barthélémy"},
{ "jour": "25", "nom": "Louis"},
{ "jour": "26", "nom": "Natacha"},
{ "jour": "27", "nom": "Monique"},
{ "jour": "28", "nom": "Augustin"},
{ "jour": "29", "nom": "Sabine"},
{ "jour": "30", "nom": "Fiacre"},
{ "jour": "31", "nom": "Aristide"}
]}' 

saint_config_sep='{ "devices":[
{ "jour": "01", "nom": "Gilles"},
{ "jour": "02", "nom": "Ingrid"},
{ "jour": "03", "nom": "Grégoire"},
{ "jour": "04", "nom": "Rosalie"},
{ "jour": "05", "nom": "Raïssa"},
{ "jour": "06", "nom": "Bertrand"},
{ "jour": "07", "nom": "Reine"},
{ "jour": "08", "nom": "Nativité de N.D."},
{ "jour": "09", "nom": "Alain"},
{ "jour": "10", "nom": "Inès"},
{ "jour": "11", "nom": "Adelphe"},
{ "jour": "12", "nom": "Apollinaire"},
{ "jour": "13", "nom": "Aimé"},
{ "jour": "14", "nom": "La St Croix"},
{ "jour": "15", "nom": "Roland"},
{ "jour": "16", "nom": "Edith"},
{ "jour": "17", "nom": "Renaud"},
{ "jour": "18", "nom": "Nadège"},
{ "jour": "19", "nom": "Emilie"},
{ "jour": "20", "nom": "Davy"},
{ "jour": "21", "nom": "Mathieu"},
{ "jour": "22", "nom": "Maurice"},
{ "jour": "23", "nom": "Constant"},
{ "jour": "24", "nom": "Thecle"},
{ "jour": "25", "nom": "Hermann"},
{ "jour": "26", "nom": "Damien"},
{ "jour": "27", "nom": "Vincent de Paul"},
{ "jour": "28", "nom": "Venceslas"},
{ "jour": "29", "nom": "Gabriel et Michel"},
{ "jour": "30", "nom": "Jérôme"}
]}' 

saint_config_oct='{ "devices":[
{ "jour": "01", "nom": "Thérèse"},
{ "jour": "02", "nom": "Leger"},
{ "jour": "03", "nom": "Gérard"},
{ "jour": "04", "nom": "François d Ass."},
{ "jour": "05", "nom": "Fleur"},
{ "jour": "06", "nom": "Bruno"},
{ "jour": "07", "nom": "Serge"},
{ "jour": "08", "nom": "Pelagie"},
{ "jour": "09", "nom": "Denis"},
{ "jour": "10", "nom": "Ghislain"},
{ "jour": "11", "nom": "Firmin"},
{ "jour": "12", "nom": "Wilfried"},
{ "jour": "13", "nom": "Geraud"},
{ "jour": "14", "nom": "Juste"},
{ "jour": "15", "nom": "Thérèse d Avila"},
{ "jour": "16", "nom": "Edwige"},
{ "jour": "17", "nom": "Baudouin"},
{ "jour": "18", "nom": "Luc"},
{ "jour": "19", "nom": "René"},
{ "jour": "20", "nom": "Adeline"},
{ "jour": "21", "nom": "Céline"},
{ "jour": "22", "nom": "Elodie"},
{ "jour": "23", "nom": "Jean de C."},
{ "jour": "24", "nom": "Florentin"},
{ "jour": "25", "nom": "Crepin"},
{ "jour": "26", "nom": "Dimitri"},
{ "jour": "27", "nom": "Emeline"},
{ "jour": "28", "nom": "Simon et Jude"},
{ "jour": "29", "nom": "Narcisse"},
{ "jour": "30", "nom": "Bienvenue"},
{ "jour": "31", "nom": "Quentin"}
]}' 

saint_config_nov='{ "devices":[
{ "jour": "01", "nom": "Toussaint "},
{ "jour": "02", "nom": "Défunt"},
{ "jour": "03", "nom": "Hubert"},
{ "jour": "04", "nom": "Charles"},
{ "jour": "05", "nom": "Sylvie"},
{ "jour": "06", "nom": "Bertille"},
{ "jour": "07", "nom": "Carine"},
{ "jour": "08", "nom": "Geoffroy"},
{ "jour": "09", "nom": "Théodore"},
{ "jour": "10", "nom": "Léon"},
{ "jour": "11", "nom": "Armistice 1918"},
{ "jour": "12", "nom": "Christian"},
{ "jour": "13", "nom": "Brice"},
{ "jour": "14", "nom": "Sidoine"},
{ "jour": "15", "nom": "Albert"},
{ "jour": "16", "nom": "Marguerite"},
{ "jour": "17", "nom": "Elisabeth"},
{ "jour": "18", "nom": "Aude"},
{ "jour": "19", "nom": "Tanguy"},
{ "jour": "20", "nom": "Edmond"},
{ "jour": "21", "nom": "Présent. Marie"},
{ "jour": "22", "nom": "Cécile"},
{ "jour": "23", "nom": "Clément"},
{ "jour": "24", "nom": "Flora"},
{ "jour": "25", "nom": "Catherine"},
{ "jour": "26", "nom": "Delphine"},
{ "jour": "27", "nom": "Séverin"},
{ "jour": "28", "nom": "Jacques de la M."},
{ "jour": "29", "nom": "Saturnin"},
{ "jour": "30", "nom": "André"}
]}' 

saint_config_dec='{ "devices":[
{ "jour": "01", "nom": "Florence"},
{ "jour": "02", "nom": "Viviane"},
{ "jour": "03", "nom": "Xavier, Fr.-Xavier"},
{ "jour": "04", "nom": "Barbara"},
{ "jour": "05", "nom": "Gerald"},
{ "jour": "06", "nom": "Nicolas"},
{ "jour": "07", "nom": "Ambroise"},
{ "jour": "08", "nom": "Immaculée Conception"},
{ "jour": "09", "nom": "Pierre Fourier"},
{ "jour": "10", "nom": "Romaric"},
{ "jour": "11", "nom": "Daniel"},
{ "jour": "12", "nom": "Chantal et Jeanne"},
{ "jour": "13", "nom": "Lucie"},
{ "jour": "14", "nom": "Odile"},
{ "jour": "15", "nom": "Ninon"},
{ "jour": "16", "nom": "Alice"},
{ "jour": "17", "nom": "Gael"},
{ "jour": "18", "nom": "Gatien"},
{ "jour": "19", "nom": "Urbain"},
{ "jour": "20", "nom": "Abraham"},
{ "jour": "21", "nom": "Pierre Canisius"},
{ "jour": "22", "nom": "Françoise-Xaviere"},
{ "jour": "23", "nom": "Armand"},
{ "jour": "24", "nom": "Adèle"},
{ "jour": "25", "nom": "Noël"},
{ "jour": "26", "nom": "Etienne"},
{ "jour": "27", "nom": "Jean"},
{ "jour": "28", "nom": "Innocent"},
{ "jour": "29", "nom": "David"},
{ "jour": "30", "nom": "Roger"},
{ "jour": "31", "nom": "Sylvestre"}
]}'




